import Link from "next/link";
import TerminalWindow from "@/components/TerminalWindow";
import RecruiterSnapshot from "@/components/RecruiterSnapshot";
import ExperienceTimeline from "@/components/ExperienceTimeline";
import SkillsGrid from "@/components/SkillsGrid";
import ProjectCard from "@/components/ProjectCard";
import Reveal from "@/components/Reveal";
import CommandPalette from "@/components/CommandPalette";
import ScrambleIntro, { ScrambleText } from "@/components/ScrambleIntro";
import { profile } from "@/data/profile";
import { projects } from "@/data/projects";
export default function Home() { return <div className="page-shell space-y-7"><TerminalWindow title="~/command-center"><div className="hero-grid relative"><ScrambleIntro /><div><p className="text-amber">$ whoami</p><h1 className="mt-4 text-3xl font-semibold text-green sm:text-5xl"><ScrambleText text={profile.name} /></h1><p className="mt-4 text-lg text-cyan"><ScrambleText text={profile.role} /></p><p className="mt-5 max-w-2xl text-sm leading-7 text-term-fg"><ScrambleText text="Database and data engineer building scalable, AI-ready infrastructure for reliable, observable systems." /></p><div className="mt-7 flex flex-wrap gap-3"><Link className="button-primary" href="/projects">$ ls projects</Link><Link className="button-secondary" href="/resume">$ cat resume</Link><Link className="button-secondary" href="/contact">$ contact</Link></div></div><aside className="terminal-card relative overflow-hidden p-4 text-sm"><div className="orbital-core" aria-hidden="true"><i /><b /><em /></div><div className="relative z-10"><p className="terminal-label">SYSTEM STATUS</p><dl className="mt-4 space-y-3"><div><dt className="text-cyan">current_role</dt><dd>Oracle DBA / DBA L1</dd></div><div><dt className="text-cyan">location</dt><dd>{profile.location}</dd></div><div><dt className="text-cyan">availability</dt><dd className="text-green">open to relevant opportunities</dd></div><div><dt className="text-cyan">focus</dt><dd>data engineering + AI infrastructure</dd></div></dl></div></aside></div><div className="mt-7"><CommandPalette /></div></TerminalWindow><Reveal><RecruiterSnapshot /></Reveal><section><p className="terminal-label">SELECTED WORK</p><h2 className="mt-2 text-2xl text-green">$ ls featured-projects/</h2><div className="mt-5 grid gap-5 md:grid-cols-3">{projects.slice(0, 3).map((project) => <ProjectCard key={project.slug} project={project} />)}</div><Link className="terminal-link mt-5 inline-block" href="/projects">view all projects →</Link></section><section className="grid gap-7 lg:grid-cols-2"><Reveal><div><p className="terminal-label">CAREER LOG</p><h2 className="mt-2 text-2xl text-green">$ git log --experience</h2><div className="mt-5"><ExperienceTimeline compact /></div><Link className="terminal-link mt-5 inline-block" href="/experience">read full experience →</Link></div></Reveal><Reveal delay={0.08}><div><p className="terminal-label">TECHNOLOGY STACK</p><h2 className="mt-2 text-2xl text-green">$ skills --summary</h2><div className="mt-5"><SkillsGrid /></div><Link className="terminal-link mt-5 inline-block" href="/skills">inspect full stack →</Link></div></Reveal></section></div>; }
